### ISSUE TITLE
Issue on update product routes

### ISSUE THREAD

**Issue by JokyOFC** [EvertonMutti/API_Shopping#5]
Na rota de produtos, ao dar um update ele não aceita devido a uma dependência do id que está no Schema do produto.

**Comment by EvertonMutti** [comment]
Mude o atributo produtos_id do schema Produto e coloque o Optional:

class Produto(BaseModel):
    produtos_id : Optional[int]  = None
    nome: str
    preco: float
    descricao: str
    codigo: str
    is_Published: Optional[bool] = False
    categoria_categoria_fk: int
